name: bird
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  code_forge: ^10.9.0
  window_manager: ^0.5.1
  re_highlight: ^0.0.3
  provider: ^6.1.5+1
  file_picker: ^10.3.8
  file_icon: ^1.0.0
  xterm: ^4.0.0
  flutter_pty: ^0.4.2
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
