name: bird
description: "An IDE for Flutter written in Flutter"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

dependencies:
  flutter:
    sdk: flutter

  #Editor Core
  code_forge: ^10.11.0
  re_highlight: ^0.0.3

  #Terminal
  xterm: ^4.0.0
  flutter_pty: ^0.4.2

  #State Management
  provider: ^6.1.5+1

  #File System
  file_picker: ^10.3.8
  file_icon: ^1.0.0

  #UI
  window_manager: ^0.5.2
  panes: ^1.3.0
  reicon_flutter: ^1.0.1

  #Utils
  path: ^1.9.1
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: FiraCode
      fonts:
        - asset: assets/fonts/Fira_Code/static/FiraCode-Regular.ttf
        - asset: assets/fonts/Fira_Code/static/FiraCode-Light.ttf
          weight: 300
        - asset: assets/fonts/Fira_Code/static/FiraCode-Medium.ttf
          weight: 500
        - asset: assets/fonts/Fira_Code/static/FiraCode-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Fira_Code/static/FiraCode-Bold.ttf
          weight: 700
